### ISSUE TITLE
Errors when following dependencies example

### ISSUE THREAD

**Issue by Ardric** [harris-chris/Jot.jl#21]
Good afternoon,

I'm rather new to Julia and am trying to follow along in the "To make a script with dependencies into a Lambda function..." example but I ran into issues when including the 1st and 3rd arguments below when calling the "create_local_image" method.

julia> ex1_local_image = create_local_image("ex1", ex1_responder; dependencies=["MySQL", "DBInterface", "DataFrames"])
ERROR: MethodError: no method matching create_local_image(::String, ::LocalPackageResponder{String}; dependencies=["MySQL", "DBInterface", "DataFrames"])

When I make the call only specifying the responder, I am able to move forward but run into a 2nd error 

julia> ex1_local_image = create_local_image(ex1_responder)
ERROR: failed process: Process(`aws configure get region`, ProcessExited(1)) [1]

Where it seems I'm missing aws configuration details. I see where I can pass in details with the 3rd argument in the function definition but I'm unsure exactly what to pass.

Can you help me understand why the 1st snippet fails? It seems that it doesn't know what the dependencies argument is even though it is used in the example. Also, could you help me understand what I would need to pass for aws configuration to prevent the 2nd error?

Thanks!

**Comment by harris-chris** [comment]
Good afternoon! You may be new to Julia but I am the one at fault here rather than you - despite what the documentation says, dependencies should be a keyword argument to `get_responder` rather than `create_local_image` - so if you do, for example```
ex1_responder = get_responder("/path/to/script.jl", :response_func, Dict; dependencies=["MySQL", "DBInterface", "DataFrames"])
ex1_local_image = create_local_image("ex1", ex1_responder)
```
Then that should work, please let me know if it doesn't. Just going to fix the documentation now.

For the second issue, the conventional way to have AWS set up on your system is to have the aws cli 2 tool installed (https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html), and to set up your identity on that - if this is the case, Jot can pick this data up directly. Could I check what output you get if you type `aws configure list-profiles` into a terminal? This should show your configured AWS identities.
