### ISSUE TITLE
Running commands with Sudo?

### ISSUE THREAD

**Issue by davibarreira** [harris-chris/Jot.jl#31]
Hey Harris, thanks a lot for the package. I'm trying to use it, but my docker command requires using `sudo`, hence I get an error when trying to run the  code as a normal user in Julia. I don't want to have to run the whole script as a root user, as this seems unsafe. I wonder if you have any work around?

**Comment by harris-chris** [comment]
Hi Davi,

There's not currently a work-around for this built into Jot. The most
direct path to a solution would be to enable you to run docker as yourself,
by adding yourself to the docker user group - like this
https://docs.docker.com/engine/install/linux-postinstall/. Unless you're in
a corporate environment or some situation where you can't do that?

**Comment by davibarreira** [comment]
I see... Yeah, I was trying to avoid granting me the privileges. I was thinking of trying to add the `sudo` to where the package calls the docker function to be ran in the terminal. This way, I could avoid having to grant privileges and stripping it off after using the package. Also, only the commands with the necessary privileges would use the privileges. Would that be a feasible solution?

**Comment by harris-chris** [comment]
Yes, I think that adding sudo to the start of some of the bash calls would
probably work. I wouldn't like to support this is a mainstream feature of
Jot, because a) I can't remember how much of the Dockerfile is
user-dependent, and b) I think that running as sudo would probably not work
for some users (myself included), but if you'd like to make a fork then I
think it would be a pretty simple change.

**Comment by davibarreira** [comment]
Thanks. I'll try that.
