### ISSUE TITLE
404 Not Found on runtime invocation after precompilation tests

### ISSUE THREAD

**Issue by sklink** [harris-chris/Jot.jl#36]
We've move to use `package_compile=true` and our build is throwing after running the the Julia tests. Could be to do with the fact that we're running Jot within an Ubuntu Docker and are missing a package.

**Error message**
```
value.(c) = [1.0]
     Testing MyPackage tests passed
Starting runtime at http://127.0.0.1:9001/2018-06-01/runtime/invocation/
DEBUG: 2022-11-03T17:04:49.979 3f27 ➡️   "71698432475048495645485445484947114117110116105109101471051101181119997116105111110471101011201163272848480474946491310721111151165832495055464846484649585748484913106599991011121165832424742131085115101114456510310111011658327284848046106108474946564650131067111110116101110116457610111010311610458324813101310" (write)
DEBUG: 2022-11-03T17:04:50.920 3f27 ⬅️   "HTTP/1.1 404 Not Found\r\n" (readuntil)
DEBUG:                                  "Transfer-Encoding: chunked\r\n"
DEBUG:                                  "\r\n"
DEBUG: 2022-11-03T17:04:50.946 3f27 ⬅️   "0\r\n" (readuntil)
DEBUG: 2022-11-03T17:04:50.987 3f27 ⬅️   "\r\n" (readuntil)
ERROR: LoadError: HTTP.ExceptionRequest.StatusError(404, "GET", "/2018-06-01/runtime/invocation/next", HTTP.Messages.Response:
"""
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
```

**Deploy Script**
```
import Pkg;
Pkg.add(url="https://github.com/harris-chris/Jot.jl#main");
using Jot

cd("./src/MyPackage")

Pkg.activate("./")
Pkg.instantiate()

using MyPackage

# Build the Lambda responder and image --
responder = get_responder(MyPackage, :my_package, Dict)
local_image = create_local_image(responder; image_suffix="my_package", package_compile=true)
remote_image = push_to_ecr!(local_image)
lambda_function = create_lambda_function(remote_image)
```

**Tests**
```
println("Running tests...")

using Test;
import MyPackage;

result = MyPackage.say_hello()
```

**Comment by harris-chris** [comment]
OK, sorry to hear you're having trouble there. Is this with the same
package as you showed me before? And I guess you're getting this when you
use the Jot.jl `run_test` function?

Running Julia from within a container shouldn't make a difference, I used
to do that myself. What do you mean when you say you're missing a package?

**Comment by harris-chris** [comment]
OK. Prima facie, there's nothing about that setup that should cause Jot to
break, particularly not if it works with `package_compile` off. I should
get some time for this tomorrow, I'll try to re-create your problem then.

**Comment by sklink** [comment]
I've created a public repository with a replication of the issue: https://github.com/sklink/jot-precompilation-test

**Comment by harris-chris** [comment]
Thanks - I've cloned your repo and got it working locally. The changes I had to make were:
 - A julia testsuite needs to be an `@testset` containing one or more `@test` assertions, so I've edited your `runtests.jl` accordingly. If you can run `Pkg.test("MyPackage")` then you know you have a test suite defined.
 - The second argument of `get_responder` needs to be the name of the responder function, rather than the package, otherwise Jot cannot know which function should be used to respond to calls
 - The third argument of `get_responder` needs to be the type of the input parameter of your responder function, in your original code it was `Dict` whereas the responder function took no arguments.
The validity of the arguments to `get_responder` can be checked at run-time and I should probably add some validation for them so that meaningful errors are produced.
I'll make a pull request on your repo to share these changes at some point tomorrow, I've got to go and do something now.
Looking at this did reveal a bug which I was unaware of so it's been a useful exercise.

**Comment by harris-chris** [comment]
Actually, I haven't got this working. As you say, setting `package_compile` to `true` causes it to break. There's some kind of error showing as to what went wrong, but it's occurring from within the docker build process so it's not easy to see what's going on.
I'm going to:
- Refactor the unit tests, which should have picked this up
- Upgrade Jot to use PackageCompiler v2
- ... then make things work again
All in all this could take a couple of weeks. Are you OK to run the function without package compilation up until that point?

**Comment by harris-chris** [comment]
My fork here: https://github.com/harris-chris/jot-precompilation-test

**Comment by harris-chris** [comment]
OK, I have my fork working (with `package_compile` as `true`). The issue seems to be that PackageCompiler v1 isn't compatible with Julia 1.8.2, so I've reverted the default Julia version to 1.6.7 until I can upgrade to PackageCompiler v2.

**Comment by sklink** [comment]
Great, compiling for me now as well -- we're returning a result in ~20ms, so excited! Thanks for taking the time!
